### ISSUE TITLE
Consistently getting NULL results while streaming

### ISSUE THREAD

**Issue by BeanStalka** [NateRickard/Xamarin.Cognitive.BingSpeech#14]
Admittedly I have a weird implementation. 

I am using the AudioStream class from your other package as a stream splitter

I have two 3rd parties at play.   One handles the Wake Word and Silence Detection 
The other handles translating the audio to text for further processing.

When I hear the wake word, I begin writing to the stream that I feed to Bing:

//this houses the streams, fliping this flag will start copying data to the   audioInputProvider.SttStream          
audioInputProvider.CaptureSttAudio = true;

//task that stops the STT
            var triggerTask = Task.Run(() =>
            {
                while (_audioInputProvider.CaptureSttAudio)
                {
                    Task.Delay(30);
                }
                    _logManager.Debug(nameof(SensorySpeechCaptureManager), "STT Trigger Task Has Finished");
            });

_sttStreamingTask = _bingSpeechApiClient.SpeechToTextSimple(_audioInputProvider.SttStream, SensorySettings.SampleRate, triggerTask);

This all works, except when  I await the _sttStreamingTask, it always returns null.  Or worse it hangs.

Is there any way get some more logging or peek into why the result is null.  My usual suspects (output window & Android Device Monitor)  are not showing me any errors.

UPDATE:
I am seeing these errors in the logcat:
09-24 17:42:54.365 E/AudioRecord-JNI(20755): Error -4 during AudioRecord native read
[0:] AudioStream.Record(): readResult returned error code: -1

Any thoughts you may have would be greatly appreciated.

P.S. - I have a simple test app that uses your package and it really fast.  I really just need to know how to step into the package and find the issue.  So I can get the same performance as the sample app.

Thanks,

BeanStalka

**Comment by nexxuno** [comment]
Hi,
you might be having the same problem I'm facing in issue #11 which wasn't solved by the fix. To debug this you have to download the project and add it to your solution and reference it instead of the nuget package.

I'm debugging on my side but not understanding much at the moment...

**Comment by BeanStalka** [comment]
Nexxuno,

I seems like it.  I have pulled down the latest and am debugging now.

I will report here with my findings

wish me luck

Bean

UPDATE:

I was able to get one request to recognize before the Bing Speech services began sending back the "Service Unavailable" error message

Authentication, Maybe?

![bingserviceerror](https://user-images.githubusercontent.com/2230503/46015331-0bcbb500-c0a0-11e8-85bc-a1ddd7fbf90b.PNG)

**Comment by NateRickard** [comment]
Re: the service unavailable error:

Assume this is Android... change your Android project to [use the Android HttpClient/Handler](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows).  This now seems to be required to successfully make calls to the speech api and I need to update the readme to reflect that.

Re: the initial reported issue here:

That error seems to be coming from [here](https://github.com/NateRickard/Plugin.AudioRecorder/blob/947bcea209b71d1c291f3989c834609b27c6fb60/Plugin.AudioRecorder.Android/AudioStream.cs#L193).  -1 is a generic 'Error' state, but interesting that a -4 is also being logged from the native code - I'm not sure what error -4 corresponds to.  

If you look at that code, I try to handle the case where we have > 1 bad reads and just auto stop the recording.  I'm not sure this has ever truly been tested since I have no way to simulate bad reads... I'd be interested to know what you find in your debugging.

**Comment by NateRickard** [comment]
Also, re: null results, the only way to really get a null response back now is if [SendRequest](https://github.com/NateRickard/Xamarin.Cognitive.BingSpeech/blob/e0d4e0b649855d7b82a6829da7f8e98af86aae3e/Xamarin.Cognitive.BingSpeech/BingSpeechApiClient.cs#L163) were to return null.  This should happen far less than it used to since we now propagate any exceptions and throw a few of our own.  Let me know what you find.

**Comment by nexxuno** [comment]
Great find! it finally works, thanks.

For further reading: https://docs.microsoft.com/it-it/xamarin/android/app-fundamentals/http-stack?tabs=windows

"April, 2018 – Due to increased security requirements, including PCI compliance, major cloud providers and web servers are expected to stop supporting TLS versions older than 1.2. Xamarin projects created in previous versions of Visual Studio default to use older versions of TLS.

In order to ensure your apps continue to work with these servers and services, you should update your Xamarin projects with the Android HttpClient and Native TLS 1.2 settings shown below, then re-build and re-deploy your apps to your users."

**Comment by BeanStalka** [comment]
Nate,

"Assume this is Android... change your Android project to use the Android HttpClient/Handler. "

That was it alright.

I still get the task hanging once in a blue moon (1/100).  When this happens my app is dead in the water.

When you throw the errors in the BingSpeechApiClient, they defiintely show up in the output, but I am left waiting indefinitely on the task i.e.

var recoResult  = await _bingSttTask;<-- if an error occurs here, I am waiting forever.

Any chance we could return a Faulted status or anything really.  So I  can handle that and restart my wake word listening task?

Also, If you want me to put in a new issue, I will.  Just let me know

FYI: currently using this:

                var sttResult = new RecognitionSpeechResult { DisplayText = "" };

                if (_sttStreamingTask.IsFaulted)
                {
                    _logManager.Error(nameof(SensorySpeechCaptureManager), "STT Encountered an error.");
                }
                else
                {
                    sttResult = await _sttStreamingTask;
                }


Thanks,

Bean

**Comment by nexxuno** [comment]
After more testing I have 100% good results while on wifi, and 100% errors while on 4G / LTE. I'll look further into it tomorrow (hopefully).
________________________________

**Comment by nexxuno** [comment]
Spoke too soon it's very hit or miss on wifi too.
________________________________

**Comment by nexxuno** [comment]
Had the time to test this on iOS too with the usual code you can find in #11 , I think the problem is deeper than changing the httpclient, I get the same error on iOS:

SendRequest: Non-success status received :: Status Code: ServiceUnavailable; Reason: Service Unavailable; Content: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img { border:0 none; }#content { margin-left: auto; margin-right: auto }#logo { margin-top: 30px; width=120px; height=34px }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Bing</title></head><body><div id='content'><div id='logo'><img alt='Bing' src='data:image/gif;base64,R0lGODlheAAiAMQAAL/a9ECR3n+16e/2/BB11jCI28/j95/I7mCj5K/R8d/t+XCt5iB+2f+mFI++7FCa4f/u0/+sI/+xMZvF7v/YmP/04v/dpwBs0////wAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAB4ACIAAAX/ICCMAmaeaKqekNQ0kbXOdG3feI4JV3/ptMhrCAEaj8gcz5dECYeNYnNKNS571dYrQql6v7XrT6UAmAG5itQ2OAMUScPZkFI4HoEeYBIIOBwTXmInCQgFPogMDw5wSHZ5iD4BAnQ2BguHkRcFCwmQiGgCAAUFaFViAwIEmqwXCJUom3mmJwCfrZIHM7a4vRdoBwYjsFNiqz4ECA5nBwsMkQsDsT60Aw+RDMpmzZmSjScIkQWiAAkC3ay0YDusDLq7twXSJqAmA+gB6ii8yLDh3itGIUKwboWYHgjm1TiASB49aiY+EUhwA8CxTSbEEKzxrwfFgigObsTB0MeDh3ow/xioh2OljwQDLha4MeBZDwYgQyYysgARnHpXZur4hAAAonc2HCAiVlAM0hwKEJWo1zEAkCt+WNowCjEnOx/fdHSzWu+TVR1YuXrEobRrTlRHxmIoK+mqpAGITt6weYGAVxNqL3zUgdfHgrkQzdrtYbWnj6crOl4o8RfDxbM62qaky3jxBav3EEVbYa1h5YxHdRi4jPIXBsVo62IIjWzBGwwKCl288EBhZXSQZ6zu1xoNbCWyM+7GRSD4X9o9HoRNkQoRAVicP3vGbM8Bula9T6MonfcArdwIdhcglp37Daw0ypFI4Mk609P8fN0Mnn0kDvhAHHARAb6Jp5IzzCEwWIAKffRBxwINOkfDAQ0eZkQCAxlIGgAHkLDMdBoiIVmBIZYIUkkpmagiSBi6teKLVTjWA4gwwsgXgZawVuOOhDRE4gkGoHMfjy+i2JcABaaym4RErpjAcgEsIIAh2OjT5I5K+sIAkld2aU8CEPLFwCQA/OglkQMMoIABbCqQpokhAAA7'/></div><div id='message'><h2>Bing services aren't available right now</h2><p>We're working to restore all services as soon as possible.<br/>We know you want to get back to searching. Please check back soon.</p></div><div id='errorref'><span>Ref A: C1DE93E158A444CBB1A9B232F7B8181A Ref B: MIL30EDGE0115 Ref C: 2018-09-26T16:06:53Z</span></div></div></body></html>


Main thread

    Xamarin.Cognitive.BingSpeech
    BingSpeechApiClient+<SendRequest>d__42.MoveNext ()
    System.Runtime.CompilerServices
    TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
    System.Runtime.CompilerServices
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
    System.Runtime.CompilerServices
    TaskAwaiter`1[TResult].GetResult ()
    Xamarin.Cognitive.BingSpeech
    BingSpeechApiClient+<SpeechToTextDetailed>d__53.MoveNext ()
    System.Runtime.CompilerServices
    TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
    System.Runtime.CompilerServices
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
    System.Runtime.CompilerServices
    TaskAwaiter`1[TResult].GetResult ()
    BeltMap.Services
    BingSpeechToText+<AcquireAsync>d__7.MoveNext ()

**Comment by NateRickard** [comment]
@BeanStalka re: awaiting that Task... any exception throw in the client should get surfaced, and if you're awaiting the Task returned from the `SpeechToText` call, it should fail and drop you into any catch block you have surrounding the call.

If I synthesize an exception in the client, the sample app has no issues completing the await and jumping to the catch block.  Faulted Tasks [should also raise exceptions when you await them](https://stackoverflow.com/questions/26078397/what-happens-when-you-await-a-failed-task) so I'm not really sure why the code you pasted is needed, even if you keep a reference to the Task and await it later as you're doing.

The Task should be faulted strictly via the magic of using async/await and having an exception occur during the awaited code. i.e. returning a faulted status should not be a manual thing but just happen when the runtime sets the exception to the Task.

Any other info you can provide to help reproduce this?  Is it possible that the triggerTask is not completing and that's causing it to never complete?  [Looking at the code](https://github.com/NateRickard/Xamarin.Cognitive.BingSpeech/blob/e6db514c42f103d1b05c1929c03b98c090e34371/Xamarin.Cognitive.BingSpeech/BingSpeechApiClient.cs#L320) I can see there may be an issue if your recording task never completes.  Probably need to add in a timeout that matches the speech api's limit.  My recording plugin auto completes after a timeout but your custom implementation may not?

**Comment by NateRickard** [comment]
And re: ServiceUnavailable error, let's keep all discussion on that in #15

**Comment by BeanStalka** [comment]
Nate,

I updated my code to use a try catch around the await of that task.

I am able to capture the error and respond accordingly.

Thanks,

Bean

**Comment by BeanStalka** [comment]
I am closing this issue since my reaming issues are around the 'Service Unavailable'
