### ISSUE TITLE
[Request] upgrade from bing service to speech service?

### ISSUE THREAD

**Issue by nexxuno** [NateRickard/Xamarin.Cognitive.BingSpeech#16]
Hello,
do you plan on supporting the new speech service or do we just need to change the endpoints? 

I'm referring to this change:

"The new Speech Service and SDK is replacing Bing Speech, which will no longer work starting October 15, 2019. For information on switching to the Speech Service, see Migrating from Bing Speech to the Speech Service."

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-migrate-from-bing-speech

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-apis

Thanks,
 Paolo

**Comment by NateRickard** [comment]
Yes, when I find time I'd like to migrate this so that it handles the newer service.  I'm not quite sure yet how much work will be required or if the API has remained very similar...

**Comment by nexxuno** [comment]
I still have to look into it too, I received an azure notification email so I asked. We still have an year to think about it!

**Comment by BeanStalka** [comment]
Hello,

Do we have an update on this?

Its been seven months since this post.

Currently I am using this NuGet package, but I need to cut over to the new services.

I was not a big fan of MS last attempt at the SDK, so I would prefer to continue using this NuGet Package and just update.

Please advise.

BeanStalka

UPDATE:

I chatted with microsoft support about the cut over.  

See transcript below

Cody: Hello, my name is Cody Farmer. What can I help you with today?

Me: I got an email about Bing Speech API being retired

Cody: Yes, that's correct. We have some information on the retirement process here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-migrate-from-bing-speechThe service will shutdown on October 15th, 2019.

Me: I currently do not have the SDK installed on my android app. I am handling it via http calls. Can I do something similar with the new Speech Services?

Cody: Yes, totally. How are you using the speech API currently - speech to text?

Me: yes

Cody: You can see the REST API for it here, it's very similar: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text

Me: excellent, do you know if there is a document listing what is different ?

Cody: The Speech Services REST APIs are compatible with the Bing Speech APIs. If you're currently using the Bing Speech REST APIs, you need only change the REST endpoint, and switch to a Speech Services subscription key.

Me: ahh, that is great news.thank you so much for your time. I think I have enough to dig into here. You have been very helpful

Cody: glad to hear it! Don't hesitate to open another ticket and let us know if you run into any issues or have any other questions.

**Comment by BeanStalka** [comment]
All, 

Any word on this?

I'm up against a time crunch and will have to go the hard route and implement the Client SDK unless I hear something.

**Comment by nexxuno** [comment]
Hi, as far as I know you only have to use the new endpoints and that's it. You can change the endpoint with the current API of this library, you could give it a try and let us know, I'll need to do it too...

**Comment by NateRickard** [comment]
Would love to hear if changing the endpoint works.  I'll be digging into this sometime soonish.

**Comment by maithakh** [comment]
Me too, I would like to know the steps for migration as speech stopped working in our production bot.

**Comment by nexxuno** [comment]
The service will be up far many months so you probably have another issue on your bot.

**Comment by maithakh** [comment]
@nexxuno actually we were using Custom Speech

**Comment by BeanStalka** [comment]
Hey guys,

I'm attempting to override the endpoints.

Does this look like the correct approach to do so?

I'm not asking about the url content, but rather the protocol string (param 1) and port (param 3).

        private Endpoint _authEndpoint = new Endpoint("https","eastus.api.cognitive.microsoft.com",443, "sts/v1.0/issuetoken");
        private Endpoint _recoEndpoint = new Endpoint("https", "eastus.stt.speech.microsoft.com", 443, "speech/recognition/conversation/cognitiveservices/v1");

Please let me know if this is the correct way to override the endpoints.

Once i get a test, I will post the results here

**Comment by nexxuno** [comment]
Sorry but I didn't have the time to play with this yet. Please let us know what you find out!

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by BeanStalka** [comment]
OK, 

I have got it working, at least with Android.  I am not setup to test iOS.

It required a few changes so I made a pull request

https://github.com/NateRickard/Xamarin.Cognitive.BingSpeech/pull/21

Please take a look.
Hopefully this will assist in getting a new version of this package out there.

Thanks,

Bean

**Comment by BeanStalka** [comment]
Hey Guys,

Its been about a week and I was hoping for a status update?

Any chance of incorporating the changes above?

Several of us on this thread are waiting to cut over to the new Speech Service.

**Comment by NateRickard** [comment]
New package published: https://www.nuget.org/packages/Xamarin.Cognitive.Speech/1.0.0

!NOTE! the name change to this repo and the package.

**Comment by BeanStalka** [comment]
Nate,

Thank you so much.

I will pull this repo down and give it a spin.

Bean
