### ISSUE TITLE
Auth errors

### ISSUE THREAD

**Issue by donbing** [NateRickard/Xamarin.Cognitive.BingSpeech#19]
i need to use westus.api.cognitive.microsoft.com for the auth uri

but the constructor on the BingSpeechApiClient is creating the auth client before my property value is set.

**Comment by donbing** [comment]
# #

**Comment by donbing** [comment]
#20 PR added

**Comment by NateRickard** [comment]
Good call, I clearly never tested changing the endpoint since I didn't have another url to use :)  That said, I may refactor it to either rebuild the auth client when set or just use the constructor similar to what you did.  Leaving it as a public property when it won't actually work correctly is probably not great...

**Comment by NateRickard** [comment]
Used your PR as a basis and resolved this in d8eaa9d46186a2523a47541eedffcd3e8095fdd5

Released an updated nuget, v2.1.3
